#!/bin/bash
#SBATCH --job-name=neb_resume
#SBATCH --partition=xeon24el8
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8GB
#SBATCH --array=0-69%40
#SBATCH --output=/home/energy/s242862/logs/neb_resume_%A_%a.log

# Resume all failed NEB reactions from their last neb.db state.
# Reaction list is generated by find_failed_nebs.sh and stored in
# /home/energy/s242862/failed_neb_list.txt
#
# Submit with:
#   bash pipeline/find_failed_nebs.sh
#   sbatch pipeline/job_neb_resume.sh

set -e

LISTFILE=/home/energy/s242862/failed_neb_list.txt
SCRIPT=/home/energy/s242862/pipeline/orca_neb_resume.py

# Read the reaction entry for this array task
LINE=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" $LISTFILE)
if [ -z "$LINE" ]; then
    echo "No reaction for task $SLURM_ARRAY_TASK_ID — exiting"
    exit 0
fi

REACTION=$(echo $LINE | awk '{print $1}')
OUTPUT=$(echo $LINE | awk '{print $2}')

echo "Task $SLURM_ARRAY_TASK_ID: $REACTION -> $OUTPUT"

module load ORCA/5.0.4-gompi-2023a
module load Python/3.13.5-GCCcore-14.3.0

python3 $SCRIPT \
    --reaction "$REACTION" \
    --output   "$OUTPUT" \
    --orca-cmd orca \
    --neb-fmax   0.15 \
    --cineb-fmax 0.05 \
    --steps      500
